### ISSUE TITLE
Boot: from USB drives fail on any hardware [20190119]

### ISSUE THREAD

**Issue by mmarmm** [aarch64-laptops/prebuilt#1]
Copying the 20190119 prebuilt image to USB and attempting to boot yields three problems:

1) [Minor] Grub2 fails to find the drive, have to specify, "configfile (hd0,gpt2)/boot/grub/grub.cfg

2) [Significant] Grub2 menu is displayed as @@@@@... vs. readable text

3) [Major] No root disk is found - the current drivers/modules supplied to the initramfs do not enable usb storage for boot

Notes: a) USB works after boot and adding the booted list of modules to initramfs does fix #3 above, b) specifying, "linux (hd0,gpt2)/vmlinux ..." in grub.cfg makes #1 disappear

**Comment by jhugo** [comment]
This is not an issue with modified ubuntu grub.  Maybe someone is interested in seeing what the differences are?  Perhaps Debian or Canonical added something to make USB more friendly.

**Comment by lag-linaro** [comment]
When was the last time this was tested?

The current prebuilt image should now support booting from SD and USB flash drive.

Closing for now.  If this is still an issue, please re-open it.
