### ISSUE TITLE
upstream novamap patch into Ubuntu

### ISSUE THREAD

**Issue by mmarmm** [aarch64-laptops/prebuilt#18]
upstream novamap patch into Ubuntu

https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1814982

**Comment by RussianNeuroMancer** [comment]
https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1814982/comments/5

**Comment by lag-linaro** [comment]
Fix has been committed into; Bionic, Cosmic and Disco.
