### ISSUE TITLE
Boot: fails on the Asus NovaGo [20190119]

### ISSUE THREAD

**Issue by mmarmm** [aarch64-laptops/prebuilt#2]
Prebuilt image 20190119 fails to boot on my Asus NovaGo (835), root disk missing, no /dev/mmcblk0 appears.

This image works on both the Lenovo Miix 630 and HP Envy x2.

Note: it appears the GPIO 95 changes might impact this working on the Lenovo, only works with it set to high? Which breaks the HP.

**Comment by aarch64-laptops** [comment]
That's strange.  Boots fine on our Asus Novago.

What about the current image?

Did you try a different MMC type/class?

**Comment by aarch64-laptops** [comment]
Just tested the [current image](https://github.com/aarch64-laptops/prebuilt/raw/7645a2a2dca83f28cc8f54c2b1a060331592ac38/aarch64-laptops-bionic-prebuilt.img.xz) which boots fine on the Asus.

To ensure that we are on the same page, could you please attempt to boot the same image please?

**Comment by mmarmm** [comment]
I have two Asus NovaGo laptops (only one now :( ), the one that I no longer have did not boot with the latest prebuilt image (20190201) but the second one does, here are the only differences I know of:

Failed: TP370QL, BIOS TP370QL.261 07/26/2018

Working: TP370QL, BIOS TP370QL.257 05/22/2018

There could also be slight hardware differences? Don't upgrade the BIOS?

**Comment by aarch64-laptops** [comment]
The latest image has been tested on the 261 we have here.

**Comment by mmarmm** [comment]
With the 20190201 prebuilt image, my Asus boots but I see these messages sporadically:

[  469.304111] mmc0: tuning execution failed: -5
[  872.935564] mmc0: tuning execution failed: -5
[  945.896061] mmc0: tuning execution failed: -5
[ 1145.065952] mmc0: tuning execution failed: -5
[ 1771.771342] mmc0: tuning execution failed: -5

With the latest 20190205 prebuilt image, my Asus boots fine but then dies after 15-20 minutes with the mmc0 ext4fs becoming read only - I'll have to sit and watch to see what actually triggers it.

**Comment by aarch64-laptops** [comment]
We could never replicate these issues.  Could have been faulty H/W or MMC.

Anyway, I think the right thing to do at this point is to close the issue.

Any more problems feel free to open another one.
