### ISSUE TITLE
maybe use xubuntu as default until gpu acceleration is ready?

### ISSUE THREAD

**Issue by hexdump0815** [aarch64-laptops/prebuilt#28]
first a big thanks for your effort to get linux running on those nice arm64 laptops!

i just successfully installed your prebuilt installer on an asus novago and the process was very smooth. the only thing which was not clearly documented was that i had to go into the BDS menu and enable "first boot from usb" as i'm using a usb-stick to boot from instead of an sd-card.

according to http://git.1wt.eu/web?p=mhz.git;a=summary - which was very accurate for me in many cases so far - the cpu seems to run at 300mhz only (i assume that this is the case because there is no cpu-frequency stuff in place yet) and the ubuntu ui is running very slow. maybe it would be better to build the provided images with the xubuntu-desktop instead? it does not do all the gpu rendering the native ubuntu ui does, which has to be done by the cpu still until the gpu is useable and steals quite a few cycles from the still quite slow clocking cpu.

once more a lot of thanks for this project and your effort - keep up the good work

best wishes - hexdump

**Comment by lag-linaro** [comment]
Providing different pre-built images is currently out-of-scope.

Please feel free to either use the provided build system to create your own pre-built image, or more simply, install the `Xfce` desktop and use that instead of the provided default.

**Comment by hexdump0815** [comment]
no problem - it was just an idea

best wishes and keep up this cool project!
