### ISSUE TITLE
USB supported WiFi or Ethernet adapter

### ISSUE THREAD

**Issue by dmelgar** [aarch64-laptops/prebuilt#29]
Is there a USB supported WiFi or ethernet adapter? Can one be enabled by generating a custom build? The build isn't very useful without some internet connectivity.

Is there a mailing list where this should be posted instead?

General report running on Lenovo C630. Website says touchscreen isn't working and trackpad is, yet I observe the opposite.

**Comment by mohamedsaied** [comment]
My exact experience on C630 "General report running on Lenovo C630. Website
says touchscreen isn't working and trackpad is, yet I observe the opposite."

**Comment by lag-linaro** [comment]
The majority of USB networking dongles that have Linux drivers are enabled.

If you've found one that doesn't work, please let us know.

**Comment by lag-linaro** [comment]
So I just booted the latest pre-built image and keyboard/touchpad is working, as is touchscreen.

What image are you seeing a broken keyboard/touchpad?

**Comment by lag-linaro** [comment]
Closing this issue, as the discussion isn't actually related to the question raised.

If you see a problem with the latest prebuilt images, please raise a new issue.
