### ISSUE TITLE
Touchpad: broken on Asus NovaGo [20190119]

### ISSUE THREAD

**Issue by mmarmm** [aarch64-laptops/prebuilt#3]
Prebuilt image 20190119 fails to enable the touchpad on my Asus NovaGo (835).

Notes:

Lenovo Miix 630 working:

lenovo$ xinput
⎡ Virtual core pointer                            id=2    [master pointer  (3)]
⎜   ↳ Virtual core XTEST pointer                  id=4    [slave  pointer  (2)]
⎜   ↳ hid-over-i2c 04F3:0400 Touchpad             id=6    [slave  pointer  (2)]
⎜   ↳ hid-over-i2c 04F3:0400 Consumer Control     id=8    [slave  pointer  (2)]

Asus NovaGo broken:

asus$ xinput
⎡ Virtual core pointer                            id=2    [master pointer  (3)]
⎜   ↳ Virtual core XTEST pointer                  id=4    [slave  pointer  (2)]
⎜   ↳ hid-over-i2c 04F3:0400 Consumer Control     id=7    [slave  pointer  (2)]

**Comment by jhugo** [comment]
I suspect the hardware on the ASUS is not using a combination keyboard/touchpad like the Lenovo/HP.  Can you use the tools from acpica/org to get a dump of the ACPI?

**Comment by mmarmm** [comment]
From Win10, dump attached below:

HID\ELAN1200&COL01\4&27C92CD6&1&0000
HID\VID_04F3&UP:0001_U:0002
HID\VID_04F3&UP:0001_U:0002
HID\ELAN1200&Col01
ACPI\ELAN1200\2
HID\ELAN1200&Col02\4&27c92cd6&1&0001
HID\ELAN1200&Col03\4&27c92cd6&1&0002

[acpi-asus-dump.txt](https://github.com/aarch64-laptops/prebuilt/files/2823938/acpi-asus-dump.txt)

**Comment by aarch64-laptops** [comment]
Thank you for the ACPI dump.

Out of interest, how did you obtain the tables?

**Comment by jhugo** [comment]
Ok.  The touchpad is a separate device, still hid-over-i2c.  Its on the same i2c6 bus, but at address 0x15.  The interrupt is a gpio off the tlmm, 0x7b, level active low.  hid desc addr 1.

Also it looks like the keyboard interrupt is 0x25, which differs from the hp/lenovo

**Comment by aarch64-laptops** [comment]
Ah nice, thanks @jhugo.  I just did the same thing.

For anyone wishing to do the same, here the process:

* I used a text editor to do the following
  * Strip the DSDT line from the top
  * Remove the bottom 3 (XSDT, FACS, FACP) sections from the file
  * Strip all of the whitespace from the front of each line

Then on the command line:

```
# Remove the ASCII section from the end of each line
$ sed 's/  .*//g' acpi-asus-dump.txt > acpi-asus-dump-no-ascii.txt

# Convert the `hexdump` back into binary
$ cat acpi-asus-dump-no-ascii.txt | xxd -r > acpi-asus-dump.bin

# Install the ACPI tools (compiler)
$ sudo apt install acpica-tools

# Recompile the binary
$ iasl -d acpi-asus-dump.bin
```

**Comment by jhugo** [comment]
In the i2c6 node, do you have "clock-frequency = <400000>;" ?

For the ASUS, looks like its still GPIO 95 for card detect.  Looks like it gets grounded when a card is inserted, so should be ""cd-gpios = <&tlmm 95 GPIO_ACTIVE_LOW>;""

**Comment by mmarmm** [comment]
Are you talking about this?: https://github.com/aarch64-laptops/linux/blob/laptops/arch/arm64/boot/dts/qcom/msm8998.dtsi#L807

Testing with "cd-gpios = <&tlmm 95 GPIO_ACTIVE_LOW>;" (& the touchpad definition above) the drive fails to appear and we're stuck at the init prompt looking for the root drive.

**Comment by jhugo** [comment]
Yes.  That is the i2c change I am talking about.  If you have that already, and are still seeing the log spew, I would recommend trying https://www.spinics.net/lists/linux-input/msg59900.html

cd-gpios has nothing to do with the touchpad.  Thats the Card Detect (cd) signal for SDHCI - ie when that signal is triggered, the SDHCI driver should go see if it can detect and init a new card.  Does SD card work for you "cd-gpios = <&tlmm 95 GPIO_ACTIVE_HIGH>;" ?

**Comment by mmarmm** [comment]
I tried to get the touchpad to work but my results were confusing, I'm a bit distracted so I'll need someone else to try this or I should be able to get to this later in the week. For the SD card, my previous experiments resulted in the Asus only booting with 95 high while the others failing to boot with 95 high but I would like someone else to confirm this.

**Comment by aarch64-laptops** [comment]
The Touchpad issues are not related to SDHDI.  We should try to keep these issues separate.

Please continue SDHCI based discussions in #2

**Comment by aarch64-laptops** [comment]
Fixed by: https://github.com/aarch64-laptops/linux/commit/99ae306dcbc517cc0419d55d0982013f036c976a
