### ISSUE TITLE
This repository is over its data quota. Purchase more data packs to restore access.

### ISSUE THREAD

**Issue by andrewarrow** [aarch64-laptops/prebuilt#30]
Keep getting this error when trying to download the large git-lfs files. I've tried forking this repo and adding credits to my account. Still get same error.

**Comment by lag-linaro** [comment]
It looks like the AArch64 Projects is out of space.

Let me see what we can do about it, at least in the short term.

**Comment by andrewarrow** [comment]
thank you! Super excited to try this out on my HP Envy. (yes my friends are actually jealous of the envy.)

**Comment by lag-linaro** [comment]
Take them from here, until we get something more permanent in place:

[AArch64 Laptops Images](http://people.linaro.org/~lee.jones/aarch64laptops/)

**Comment by andrewarrow** [comment]
I get "You don't have permission to access /~lee.jones/aarch64laptops/aarch64-laptops-bionic-prebuilt.img.xz on this server.

Apache/2.4.29 (Ubuntu) Server at people.linaro.org Port 80"

**Comment by lag-linaro** [comment]
Fixed, please try again.

**Comment by andrewarrow** [comment]
works. Now I'm on to trying to get the keyboard to work on HP-Envy. Boots up fine in installer but then no way to select anything.

**Comment by lag-linaro** [comment]
Sounds like you haven't selected the correct DTB.
