### ISSUE TITLE
HP Envy x2: invalid device tree

### ISSUE THREAD

**Issue by andrewarrow** [aarch64-laptops/prebuilt#31]
I get:

```
Booting `Ubuntu GNU/Linux'

Loading Linux 5.0.1-laptops0.1-generic ...
Loading initial ramdisk ...
Loading device tree ...
error: invalid device tree.

Press any key to continue...

EFI stub: Booting Linux Kernel...
EFI stub: Using DTB from configuration table
EFI stub: Exiting boot services and installing virtual address map...

```

After booting from USB drive with the prebuilt image (aarch64-laptops-bionic-prebuilt.img) flashed on to it, and the `sudo ln -s /boot/laptop.dtb laptop-hp-envy-x2.dtb` was done.

**Comment by andrewarrow** [comment]
I get much further with `aarch64-laptops-ubuntu-bionic-installer.img` that boots into a menu with option to install Ubuntu Server. It asks for language but I cannot select anything with keyboard. I unplug usb with the img and plug in a keyboard and I am able to hit return. Then I plug back in USB Drive and continue with installation. It says detecting hardware several times but I seem to be an loop until I see E: Unimplemented feature

**Comment by andrewarrow** [comment]
Processor is Snapdragon 835 2.21 GHz, 4.00 GB RAM

**Comment by lag-linaro** [comment]
> After booting from USB drive with the prebuilt image (aarch64-laptops-bionic-prebuilt.img) flashed on to it, and the `sudo ln -s /boot/laptop.dtb laptop-hp-envy-x2.dtb` was done.

Shouldn't that be the other way around?

**Comment by andrewarrow** [comment]
hehe, yes other way around. Sorry i typed it wrong in this issue but did it right on the drive. But I went back and re-ran the script just to be sure. The script finishes without error and i'm using /dev/sdb the entire drive not /dev/sdb2 or something like that. But after i place the drive into hp envy and boot it, same error.  Maybe it's something specific with my HP Envy hardware? Any idea where to debug next? Thanks!

**Comment by lag-linaro** [comment]
Try to copy the real file to laptop.dtb:

```cp laptop-hp-envy-x2.dtb laptop.dtb```

**Comment by lag-linaro** [comment]
Please join the IRC channel #aarch64-laptops on FreeNode.

**Comment by lag-linaro** [comment]
Did you ever get to the bottom of this?

**Comment by andrewarrow** [comment]
no. Got distracted with other things, left this were it was. But if you have ideas I'm all ears.

**Comment by lag-linaro** [comment]
It's really difficult to debug these issues remotely, but I will try to help you out.

Can you join the `#aarch64-laptops` IRC channel?
