### ISSUE TITLE
Please provide status update

### ISSUE THREAD

**Issue by erik-h11** [aarch64-laptops/prebuilt#32]
I don't have a specific problem, but was just wondering about the status of this project, since there haven't been any commits since March 25. 

A few months ago, I tried booting my Yoga 630 off these images; I was able to get the system running, albeit slowly (it seemed to matter which USB key I used). That was encouraging, but the lack of Wifi meant I cannot use the machine while travelling.

I read some articles mentioning that RedHat/Fedora is going to work on supporting this architecture. Has that made this project obsolete? If not, could someone provide a status?

Thanks, Erik

**Comment by lag-linaro** [comment]
The project is still very much active.

We are currently centring our efforts on enabling the upstream kernel and working with distros, such that they will 'just work'.  Activities to update the pre-built image have been put on hold.

I have a TODO to create a public `announcements` mailing list.  Once it's up (hopefully by EoP today), you should sign-up to receive a weekly progress report.

**Comment by lag-linaro** [comment]
The new Mailing List is now up.

If you're interested in status updates, please sign-up:

https://lists.linaro.org/mailman/listinfo/aarch64-laptops

**Comment by erik-h11** [comment]
Thanks. I've signed up. 

Just my $0.02 about what is important, in my view: I don't need Linux on this machine because I hate Windows (I do, but I don't like Unix either), but because WoS is so limited. If I can boot Linux somehow, connect to my work VPN via Wifi or mobile data, and open a terminal window, I have all I need.

Thanks for doing this!
