### ISSUE TITLE
Prebuilt Images Unavailable and Docker Env. Not Working

### ISSUE THREAD

**Issue by sylentprofet** [aarch64-laptops/prebuilt#33]
```
user@box:~/aarch64-laptops/prebuilt$ git checkout .
Downloading aarch64-laptops-bionic-clean-desktop-img-xml.tgz (1.5 GB)
Error downloading object: aarch64-laptops-bionic-clean-desktop-img-xml.tgz (f98db08): Smudge error: Error downloading aarch64-laptops-bionic-clean-desktop-img-xml.tgz (f98db083e527e3681c2d1b38bf82f9fc1966ea8f2cfe0f20a10161a6af284ca9): batch response: This repository is over its data quota. Purchase more data packs to restore access.

Errors logged to /home/user/aarch64-laptops/prebuilt/.git/lfs/logs/20190618T163329.78351355.log
Use `git lfs logs last` to view the log.
error: external filter 'git-lfs filter-process' failed
fatal: aarch64-laptops-bionic-clean-desktop-img-xml.tgz: smudge filter lfs failed
```

Can you please host the prebuilt images elsewhere? Also some mention of git-lfs in the documentation would be handy, took a while to figure out what was going on there.

When trying to make images using the docker image, it seems to break, asking for sudo to be installed in the docker image. I'm trying baremetal now, but a list of dependencies to build would be nice. I was missing autoconf, a few other things.

If I try the docker image again, I'll paste the output.

Really looking forward to helping work on this, exciting project!

**Comment by rhenwood-arm** [comment]
@sylentprofet the pre-built images have been made available from here:
http://people.linaro.org/~lee.jones/aarch64laptops/

**Comment by sylentprofet** [comment]
@rhenwood-arm 

thanks! i'm going to keep working on this tonight.

**Comment by lag-linaro** [comment]
When reporting issues, could you do so separately please.

Bunching them up into a single bug report makes them difficult to triage.

**Comment by lag-linaro** [comment]
So with regards to the first issue; this is easily worked around.  As @rhenwood-arm mentioned, we are temporarily hosting images on my Linaro People page, with a view to finding a new permanent residence i the very near future.

**Comment by lag-linaro** [comment]
Docker dependencies are handled in the `Dockerfile` and should be, or at least were complete.

The trouble with using Docker is it always pulls a clean distro image and fully updates all of the packages.  If the package dependancies change, then we have to be fluid enough to provide them in the `Dockerfile`, but seeing as no one is currently building new pre-builts at the moment, these can slip through the cracks.

`sudo` should not be required inside the Docker container though, as we are already running as Superuser.  I will look into this and report back here.

So would you mind telling me why you need to build a new pre-built image please?  Perhaps I can provide you with a better means to consume the project.

**Comment by lag-linaro** [comment]
> I'm trying baremetal now, but a list of dependencies to build would be nice.

A list of dependencies can be found in the `Dockerfile`.  Although it is not expected for the vast majority of people to build their own pre-built images.

To that end, would you mind telling me why you need to build a new pre-built image please? Perhaps I can provide you with a better means to consume the project.

**Comment by lag-linaro** [comment]
> `sudo` should not be required inside the Docker container though, as we are already running as Superuser. I will look into this and report back here.

Okay, so it looks like a recent change was using `sudo` directly, instead of the dynamically set `$SUDO`.  The latter ensures `sudo` is only used when building locally as opposed to inside a container.

I'll fix and push this right away.
