### ISSUE TITLE
850: fails to boot - Lenovo Yoga C630 [20190119] 

### ISSUE THREAD

**Issue by mmarmm** [aarch64-laptops/prebuilt#4]
Prebuilt image 20190119 fails to boot on my Lenovo Yoga C630 (850).

Notes: the kernel loads up to the four EFI stub messages then nothing after that and the system appears locked up; using the sdm845-mtp.dtb boots the kernel until:
... 
[ 2.3...] Internal error: Oops: 96000004 [#1] SMP
...
pc : clk_hw_get_rate+0x1c/0x48
lr : _freq_tlb_determine_rate+0xec/0x110
...
Begin: Loading essential drivers ...
[ 364.0...] usbcore: ...
...
[ 365.8...] sdhci-pltfm: SDHCI platform and OF driver helper
<< HANGS HERE >>

**Comment by jhugo** [comment]
850 is a different chip than 835, and will require a different DT.  I don't think there will be a way to configure GRUB to detect the chip and automatically select the correct DT.  What about having GRUB stop at the GRUB menu, and having a 835 and 850 option?

The prebuilt kernels are 835 focused, so they may not have all of the 850 (845) entities built, or built in.

**Comment by aarch64-laptops** [comment]
835 is the current focus. Please bear with us.

**Comment by mmarmm** [comment]
TODO: dump ACPI tables so someone can figure out how to get the keyboard & USB drives working.

**Comment by aarch64-laptops** [comment]
Keyboard and USB already work on this platform.

**Comment by lag-linaro** [comment]
This is now fixed.

The latest prebuilt binary now boots on the Lenovo Yoga 850.
