### ISSUE TITLE
UFS: local drive inaccessible on any platform [20190119]

### ISSUE THREAD

**Issue by mmarmm** [aarch64-laptops/prebuilt#6]
Unable to access the local UFS drive on any of the platforms. Unable to install to local disk.

**Comment by jhugo** [comment]
Pull in these changes for 835-
https://patchwork.codeaurora.org/patch/701239/
https://patchwork.codeaurora.org/patch/701241/
https://patchwork.codeaurora.org/patch/701243/
https://patchwork.codeaurora.org/patch/701245/

Note, I highly recommend backing up the entire existing UFS before modifying it in any way.  It may be necessary to pull files off the Windows partition in the future to enable functionality.

**Comment by aarch64-laptops** [comment]
On the immediate TODO.  Due for enablement next week.

**Comment by mmarmm** [comment]
Couldn't get this (701241/) to apply cleanly, I'll have to wait:

>				<&rpmcc RPM_SMD_LN_BB_CLK1>,

**Comment by aarch64-laptops** [comment]
Now available in latest image.  Tested on the Asus.

Closing.
